config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
 resources :movies
   get "/movies", to: "movies#index"
   get "/omdb", to: "omdb#index"
   get "/omdb/show/", to: "omdb#show"
   get "/articles", to: "articles#index"
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
    mount_uploader :poster, PosterUploader # Tells rails to use this uploader for this model.
    validates :title, presence: true # Make sure the title is present.
end

app/models/omdb.rb
class Omdb
    # belongs_to :omdb
    def responsesearch(search)
        url="http://www.omdbapi.com/?apikey=b511989&s=" + search
        uri = URI(url)
        json =  JSON.parse(Net::HTTP.get(uri))
        return json["Search"]
    end

    def responseshow(show)
        url="http://www.omdbapi.com/?apikey=b511989&i=" + show
        uri = URI(url)
        json =  JSON.parse(Net::HTTP.get(uri))
        return json
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @test = "Olsen"
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  layout "movies_"

  def index
    @movie = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @upload = false
  end

  def new
    @movie = Movie.new
    @upload = true
  end

  def create
    @movie = Movie.new(movie_params)
    @upload = true

    if @movie.save
      redirect_to movies_path, notice: "Uploadet!"
    else
      render "new"
    end
  end
  
  def edit
    @movie = Movie.find(params[:id])
    @upload = true
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie
    else
      render :edit
    end
  end

  def destroy
    @upload = false
    @movie = Movie.find(params[:id])
    @movie.destroy

    redirect_to root_path, notice:  "Slettet" 
  end

  private
    def movie_params
      params.require(:movie).permit(:title, :description, :poster, :year, :imdbID)
    end

  end

app/controllers/omdb_controller.rb
class OmdbController < ApplicationController
  layout "movies_"

  def index
    unless params[:search].blank?
      jsonclass = Omdb.new
      @response = jsonclass.responsesearch(params[:search])
      unless (@response!=nil)
        @mess="Ikke fundet!"
      end
    else
      @mess="Indtast søgetekst"
    end
  end
  
  def show
    @b=params[:search]
    jsonclass = Omdb.new
    @movie = jsonclass.responseshow(params[:show])
  end


  private
    def omdb_params
      params.permit(:search)
      params.permit(:show)
    end

  end
  # :title, :plot, :poster, :year, :imdbID,

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/omdb_helper.rb
module OmdbHelper
end

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<h1>Articles</h1>
<%= @test %>
<ul>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filmdatabase</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/movies_.html.erb
<!DOCTYPE html>   
<html>   
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <title>Filmdatabase</title>   
      
  </head>   
  
  <body>   
    <div class="container">
      <%= yield %>     
    </div>           
  </body> 
  
</html>   

app/views/movies/_form.html.erb
<%= form_with model: movie do |form| %>
<% if !@movie.errors.empty? %>
   <div>
       <ul>
         <% @movie.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
   </div>
<% end %>
<hr>
<div class="row">
  <div class="col-sm-7">
    <div class="row">
      <div class="col-sm-4">
        <%= form.label :"Titel:" %>
      </div>  
      <div class="col-sm-8">
       <%= form.text_field :title %>
      </div>  
    </div>  
    <div class="row">
      <div class="col-sm-4">
        <%= form.label :"År:" %>
      </div>  
      <div class="col-sm-8">
        <%= form.text_field :year %>
      </div>  
    </div>  
     <div class="row">
      <div class="col-sm-4">
         <%= form.label :"ID:" %>
      </div>  
      <div class="col-sm-8">
         <%= form.text_field :imdbID %>
      </div>  
    </div>  
    <div class="row">
      <div class="col-sm-4">
        <%= form.label :"Beskrivelse:" %>
      </div>  
      <div class="col-sm-8">
        <%= form.text_area :description, cols: 30, rows: 10%>
      </div>  
    </div>  
  </div>
  <div class="col-sm-3">
    <div class="row">
      <div class="col-sm-4">
            <%= form.label :"Plakat: " %>
      </div>  
      <div class="col-sm-8">
        <% unless !@upload %>   
          <%= form.file_field :poster %>  
        <% end %>
      </div>  
      <div class="row">
        <div class="col-sm-4">
            &nbsp
        </div>  
        <div class="col-sm-8">
          <% unless movie.poster.blank? %>   
            <img src=<%= @movie.poster %> alt="Plakat" height="200">
          <% end %>
        </div>  
      </div>  
    </div>  
  </div>
</div>
<hr>
<div>
  <%= form.submit "Gem film" %>
</div>

<% end %>

app/views/movies/edit.html.erb
<%= link_to "< Tilbage ", movie_path(@movie) %>

<h1>Rediger Film</h1>

<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<h1>Film</h1>
<hr>
<h2>
  <div class="row">
    <div class="col-sm-3">Titel </div>
    <div class="col-sm-2">År </div>
    <div class="col-sm-5">Beskrivelse</div>
  </div>
</h2>
<hr>
<% @movie.each do |movie| %>
  <div class="row">
    <div class="col-sm-3"><%= link_to movie.title, movie %> </div>
    <div class="col-sm-2"><%= movie.year%> </div>
    <div class="col-sm-5"><%= movie.description %> </div>
  </div>
<% end %>
<hr>

<%= link_to "Opret ny film", new_movie_path %>

app/views/movies/new.html copy.erb
<%= link_to "< Tilbage til liste ", root_path %>
<h1>New Movie</h1>

<div class="container">
<% if !@movie.errors.empty? %>
   <div>
      
      <ul>
         <% @movie.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

   <div>
      <%= form_for @movie, html: { multipart: true } do |f| %>
      <%= f.label :Titel %><br>
      <%= f.text_field :title %><br>

      <%= f.label :År %><br>
      <%= f.text_field :year %><br>
      <br><br>
         <%= f.label :ID %><br>
      <%= f.text_field :imdbID %><br>
   <br><br>
      <%= f.label :Plakat %><br>
      <%= f.file_field :poster %>  
      <br><br>
      <%= f.label :Description %><br>
      <%= f.text_area :description %><br>
      <br><br>
      <%= f.submit "Save" %>
      <% end %>
   </div>
</div>

app/views/movies/new.html.erb
<%= link_to "< Tilbage til liste ", root_path %>
<h1>Ny film</h1>
<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<%= link_to "< Tilbage til liste ", root_path %>
<hr>
<div class="row">
  <div class="col-sm-6">
    <div class="row">
      <div class="col">
        <h1><%= @movie.title %></h1>
      </div>
    </div>  
    <div class="row">
      <div class="col-sm-4">
        År:
      </div>  
      <div class="col-sm-8">
        <%= @movie.year %>
      </div>  
    </div>  
    <div class="row">
      <div class="col-sm-4">
        ID:
      </div>  
      <div class="col-sm-8">
        <%= @movie.imdbID %>
      </div>  
    </div>  
    <div class="row">
      <div class="col-sm-4">
        Beskrivelse:
      </div>  
      <div class="col-sm-8">
        <%= @movie.description %>
      </div>  
    </div>  
  </div>
  <div class="col-sm-4">
    <div class="row">
      <div class="col-sm-4">
            Plakat:
      </div>  
      <div class="col-sm-8">
             &nbsp
      </div>  
      <div class="row">
        <div class="col-sm-4">
            &nbsp
        </div>  
        <div class="col-sm-8">
          <% unless @movie.poster.blank? %>   
            <img src=<%= @movie.poster %> alt="Plakat" height="200">
          <% end %>
        </div>  
      </div>  
    </div>  
  </div>
</div>
<hr>
<ul>
    <li><%= link_to "Rediger", edit_movie_path(@movie) %></li>
    <li><%= link_to "Slet", movie_path(@movie),
                  method: :delete,
                  data: { confirm: "Er du sikker?" } %></li>
 

</ul>

app/views/omdb/_form.html.erb
<%= form_tag(omdb_path, :method => "get")   %>
<div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Søg", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "Søg", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
    </div>  
</div>  
<hr>
   <%# <% if !@omdb.errors.empty? %>
      <%#<div>
         <%#<ul>
            <% @omdb.errors.full_messages.each do |msg| %>
            <%#   <li><%= msg </li> %>
            <%#<% end %>
         <%#</ul>
      <%#</div>
   <%# <% end %>
   <div>
      <%= yield %>
    </div>

app/views/omdb/_search.html.erb
  
<%= form_tag(omdb_path, :method => "get")   %>

  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Søg", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
    </div>  
  </div>  

app/views/omdb/index.html.erb
<h1>OMDB</h1>
 <%= render "form", omdb: @omdb %>
  <h2>
    <div class="row">
    <div class="col-sm-12"><%= @mess %> </div>
    </div>
  </h2>
  <% unless (@response==nil) %>
<h2>
  <div class="row">
    <div class="col-sm-2">Imdb Id </div>
    <div class="col-sm-2">Type </div>
    <div class="col-sm-6">Titel </div>
    <div class="col-sm-2">År</div>
  </div>
</h2>


      <% @response.each do |key| %>
        <div class="row">
          <div class="col-sm-2"><%= key["imdbID"] %> </div>
          <div class="col-sm-2"><%= key["Type"] %> </div>
          <div class="col-sm-6"><%= link_to key["Title"],:controller => "omdb", :action => "show", :show => key["imdbID"],:search => params["search"] %></div> 
          <div class="col-sm-2"><%= key["Year"] %> </div>
         </div>
      <% end %>
  <% end %>
<hr>

app/views/omdb/show.html.erb
<%= link_to "< Tilbage til liste ",:controller => "omdb", :action => "index",:search => @b %>
<hr>
<div class="row">
  <div class="col-sm-12">
    <div class="row">
      <div class="col">
        <h2><%= @movie["Title"] %></h2>
      </div>
    </div>  
  </div>  
</div>  
<div class="row">
  <div class="col-sm-8">
    <div class="row">
      <div class="col-sm-3">
        <div>År:</div>
      </div>  
      <div class="col-sm-9">
        <%= @movie["Year"] %>
      </div>  
    </div>  
    <div class="row">
      <div class="col-sm-3">
        ID:
      </div>  
      <div class="col-sm-9">
        <%= @movie["imdbID"] %>
      </div>  
    </div>  
    <div class="row">
      <div class="col-sm-3">
        Beskrivelse:
      </div>  
      <div class="col-sm-9">
        <%= @movie["Plot"] %>
      </div>  
    </div>  
  </div>
  <div class="col-sm-4">
    <div class="row">
        <div class="col-sm-12">
          <% unless @movie["Poster"]=="N/A" %>   
            <img src=<%= @movie["Poster"] %> alt="Plakat" height="200">
          <% end %>
        </div>  
    </div>  
  </div>
</div>  
<hr>